// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eilrqredlopgpoxjxqgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbHJxcmVkbG9wZ3BveGp4cWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjY3NDEsImV4cCI6MjA2NTcwMjc0MX0.hXR64SbGlLAdb0VlZyxykiKBhUAXEd7hfjHtnQ9903w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);